name: flash_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.2.beta <4.0.0'

dependencies:
  avatar_glow: ^2.0.2
  camera: ^0.10.5+5
  flutter:
    sdk: flutter
  path: ^1.8.3
  torch_controller: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
